import { GoogleGenAI } from "@google/genai";
import { ImageUpload } from "../types";

const GEMINI_API_KEY = process.env.API_KEY || '';

// Initialize the client
const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

/**
 * Helper to resize an image to a maximum dimension, reducing token usage.
 */
const resizeImage = (base64Str: string, maxDimension: number = 1024): Promise<string> => {
  return new Promise((resolve) => {
    const img = new Image();
    img.src = base64Str;
    img.onload = () => {
      let width = img.width;
      let height = img.height;

      if (width > height) {
        if (width > maxDimension) {
          height = Math.round((height * maxDimension) / width);
          width = maxDimension;
        }
      } else {
        if (height > maxDimension) {
          width = Math.round((width * maxDimension) / height);
          height = maxDimension;
        }
      }

      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext('2d');
      ctx?.drawImage(img, 0, 0, width, height);
      resolve(canvas.toDataURL('image/jpeg', 0.8)); // 0.8 quality JPEG
    };
  });
};

/**
 * Generates a virtual try-on image using Gemini.
 * @param personImage The image of the user.
 * @param clothingImage The image of the clothing item.
 * @returns The base64 data URL of the generated image.
 */
export const generateTryOnImage = async (
  personImage: ImageUpload,
  clothingImage: ImageUpload
): Promise<string> => {
  if (!personImage.base64 || !clothingImage.base64) {
    throw new Error("Images are missing base64 data.");
  }

  try {
    // 1. Resize images to reduce token count and avoid 429 Errors
    const resizedPerson = await resizeImage(personImage.base64);
    const resizedClothing = await resizeImage(clothingImage.base64);

    // 2. Strip headers for API
    const personBase64 = resizedPerson.split(',')[1];
    const clothingBase64 = resizedClothing.split(',')[1];

    // 3. Call the API with the Flash Model (Stable & Fast)
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      config: {
        generationConfig: {
          temperature: 0.1, // Very low temperature for deterministic output
        }
      },
      contents: {
        parts: [
          {
            text: `Perform a high-fidelity virtual try-on task for an Indian fashion boutique. 
            
            Inputs:
            1. 'Person Image': A photo of a customer.
            2. 'Garment Image': A photo of a specific piece of Indian ethnic clothing (e.g., Saree, Lehenga, Kurta, Sherwani).

            Task:
            Generate a photorealistic image of the person from the first image wearing the garment from the second image.

            STRICT CONSTRAINT CHECKLIST (VIOLATION = FAILURE):
            1. [CRITICAL] EXACT COLOR MATCH: The color of the garment in the output MUST be identical to the 'Garment Image'.
            2. [CRITICAL] NO HALLUCINATIONS: Do NOT add new colors, borders, sequins, or patterns that are not present in the 'Garment Image'.
            3. [CRITICAL] TEXTURE PRESERVATION: Preserve the specific fabric texture (e.g. silk, cotton, net) exactly as seen.
            4. IDENTITY PRESERVATION: Maintain the person's exact face, skin tone, body shape, and pose.
            5. REALISTIC DRAPE: Wrap the Indian garment naturally around the body using physics-based draping.
            6. BACKGROUND: Keep the original background of the 'Person Image'.

            Negative Constraints:
            - Do NOT color correct the garment.
            - Do NOT add jewelry or accessories.
            - Do NOT change the lighting of the garment.

            Output only the final image.`
          },
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: personBase64
            }
          },
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: clothingBase64
            }
          }
        ]
      }
    });

    // Extract image from response
    if (response.candidates && response.candidates.length > 0) {
      const candidate = response.candidates[0];
      if (candidate.content && candidate.content.parts) {
        for (const part of candidate.content.parts) {
          if (part.inlineData && part.inlineData.data) {
            return `data:image/png;base64,${part.inlineData.data}`;
          }
        }
      }
    }

    // Fallback if no image found directly in standard structure
    throw new Error("No image generated by the model. It might have been blocked by safety filters.");

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    if (error.message?.includes('429')) {
      throw new Error("Traffic is high. Please wait 1 minute and try again.");
    }
    throw new Error(error.message || "Failed to generate try-on image.");
  }
};